"""link visitors to users

Revision ID: 33e008c2bce2
Revises: ce9defc466f6
Create Date: 2026-08-24 23:09:13.294718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e008c2bce2'
down_revision: Union[str, Sequence[str], None] = 'ce9defc466f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visitors_user_id'), 'visitors', ['user_id'], unique=True)
    op.create_foreign_key(None, 'visitors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_index(op.f('ix_visitors_user_id'), table_name='visitors')
    op.drop_column('visitors', 'user_id')
    # ### end Alembic commands ###
