"""create feedbacks

Revision ID: 5526b7a4471e
Revises: e97b85afd5ac
Create Date: 2026-09-09 14:02:34.555060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5526b7a4471e'
down_revision: Union[str, Sequence[str], None] = 'e97b85afd5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_code', sa.String(length=50), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('exhibition_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_exhibition_id'), 'feedbacks', ['exhibition_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_feedback_code'), 'feedbacks', ['feedback_code'], unique=True)
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_status'), 'feedbacks', ['status'], unique=False)
    op.create_index(op.f('ix_feedbacks_visitor_id'), 'feedbacks', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_visitor_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_status'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_feedback_code'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_exhibition_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
