"""create exhibitions

Revision ID: 7420c0a61b61
Revises: 7da0cbb0e4ab
Create Date: 2026-08-19 21:26:40.659230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7420c0a61b61'
down_revision: Union[str, Sequence[str], None] = '7da0cbb0e4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitions_code'), 'exhibitions', ['code'], unique=True)
    op.create_index(op.f('ix_exhibitions_id'), 'exhibitions', ['id'], unique=False)
    op.create_index(op.f('ix_exhibitions_name'), 'exhibitions', ['name'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f('ix_exhibitions_name'),
        table_name='exhibitions',
    )

    op.drop_index(
        op.f('ix_exhibitions_id'),
        table_name='exhibitions',
    )

    op.drop_index(
        op.f('ix_exhibitions_code'),
        table_name='exhibitions',
    )

    op.drop_table('exhibitions')

    # ### end Alembic commands ###