"""create exhibition areas

Revision ID: 7da0cbb0e4ab
Revises: 7bbc6f5b4bc7
Create Date: 2026-08-19 17:53:33.311076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da0cbb0e4ab'
down_revision: Union[str, Sequence[str], None] = '7bbc6f5b4bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibition_areas_code'), 'exhibition_areas', ['code'], unique=True)
    op.create_index(op.f('ix_exhibition_areas_id'), 'exhibition_areas', ['id'], unique=False)
    op.create_index(op.f('ix_exhibition_areas_name'), 'exhibition_areas', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exhibition_areas_name'), table_name='exhibition_areas')
    op.drop_index(op.f('ix_exhibition_areas_id'), table_name='exhibition_areas')
    op.drop_index(op.f('ix_exhibition_areas_code'), table_name='exhibition_areas')
    op.drop_table('exhibition_areas')
    # ### end Alembic commands ###
