"""create exhibition artifacts

Revision ID: d6250552a4e0
Revises: 5526b7a4471e
Create Date: 2026-09-09 18:05:29.396482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6250552a4e0'
down_revision: Union[str, Sequence[str], None] = '5526b7a4471e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibition_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibition_artifacts_artifact_id'), 'exhibition_artifacts', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_exhibition_artifacts_exhibition_id'), 'exhibition_artifacts', ['exhibition_id'], unique=False)
    op.create_index(op.f('ix_exhibition_artifacts_id'), 'exhibition_artifacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exhibition_artifacts_id'), table_name='exhibition_artifacts')
    op.drop_index(op.f('ix_exhibition_artifacts_exhibition_id'), table_name='exhibition_artifacts')
    op.drop_index(op.f('ix_exhibition_artifacts_artifact_id'), table_name='exhibition_artifacts')
    op.drop_table('exhibition_artifacts')
    # ### end Alembic commands ###
